# Generated by Django 4.2.2 on 2023-10-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Salary',
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_Status',
            field=models.CharField(default='Not yet delivered.', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Parcel_Width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Parcel_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Parcel_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Receiver_Name_Employee_Id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee2', to='courier_service.employees'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Sender_Employee_Id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee1', to='courier_service.employees'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
