# Generated by Django 4.2.2 on 2023-10-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0003_alter_orders_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='To_State',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
