# Generated by Django 4.2.2 on 2023-10-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0003_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
