# Generated by Django 4.2.2 on 2023-10-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0004_alter_orders_to_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Receiver_Name_Employee_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee2', to='courier_service.employees'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Sender_Employee_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee1', to='courier_service.employees'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='User_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_service.user'),
        ),
    ]
