# Generated by Django 4.2.2 on 2023-10-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0005_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Branch_Id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Department_Id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Manager_Id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Receiver_Name_Employee_Id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Sender_Employee_Id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='User_Id',
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
