# Generated by Django 4.2.2 on 2023-10-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier_service', '0006_remove_employees_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('Branch_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(max_length=50)),
                ('Contact_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('House_No', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin_Code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employee_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Contact_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('House_No', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin_Code', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Branch_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_service.branches')),
                ('Department_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_service.department')),
                ('Manager_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_service.employees')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('Contact_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('House_No', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin_Code', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Order_Name', models.CharField(max_length=50)),
                ('Parcel_Weight', models.IntegerField()),
                ('Parcel_length', models.IntegerField()),
                ('Parcel_Width', models.IntegerField()),
                ('Parcel_height', models.IntegerField()),
                ('booked_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField(null=True)),
                ('delivered_date', models.DateTimeField(null=True)),
                ('From_House_No', models.CharField(max_length=50)),
                ('From_Street', models.CharField(max_length=50)),
                ('From_City', models.CharField(max_length=50)),
                ('From_State', models.CharField(max_length=50)),
                ('From_Pin_Code', models.IntegerField()),
                ('Receiver_Name', models.CharField(max_length=50)),
                ('To_House_No', models.CharField(max_length=50)),
                ('To_Street', models.CharField(max_length=50)),
                ('To_City', models.CharField(max_length=50)),
                ('To_State', models.CharField(max_length=50)),
                ('To_Pin_Code', models.IntegerField()),
                ('Order_Status', models.CharField(max_length=50)),
                ('Order_Type', models.CharField(max_length=50)),
                ('delivery_charge', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Receiver_Name_Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee2', to='courier_service.employees')),
                ('Sender_Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee1', to='courier_service.employees')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_service.user')),
            ],
        ),
    ]
