# Generated by Django 4.2.2 on 2023-10-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0008_user_details_alter_orders_user_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='City',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Contact_Number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='House_No',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Pin_Code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='State',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Street',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
