# Generated by Django 4.2.2 on 2023-10-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0005_alter_orders_receiver_name_employee_id_and_more'),
        ('courier_service', '0011_alter_user_details_userid'),
    ]

    operations = [
    ]
