# Generated by Django 4.2.2 on 2023-10-21 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier_service', '0012_merge_20231021_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='User_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='UserId',
            field=models.IntegerField(),
        ),
    ]
