# Generated by Django 4.2.2 on 2023-10-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0013_alter_orders_user_id_alter_user_details_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='Branch_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_service.branches'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_service.department'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='UserId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
