# Generated by Django 4.2.2 on 2023-10-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0014_remove_user_details_id_alter_employees_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Order_Name', models.CharField(max_length=50)),
                ('Parcel_Weight', models.IntegerField()),
                ('Parcel_length', models.IntegerField(blank=True, null=True)),
                ('Parcel_Width', models.IntegerField(blank=True, null=True)),
                ('Parcel_height', models.IntegerField(blank=True, null=True)),
                ('booked_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('From_House_No', models.CharField(max_length=50)),
                ('From_Street', models.CharField(max_length=50)),
                ('From_City', models.CharField(max_length=50)),
                ('From_State', models.CharField(max_length=50)),
                ('From_Pin_Code', models.IntegerField()),
                ('Receiver_Name', models.CharField(max_length=50)),
                ('To_House_No', models.CharField(max_length=50)),
                ('To_Street', models.CharField(max_length=50)),
                ('To_City', models.CharField(max_length=50)),
                ('To_State', models.CharField(max_length=50, null=True)),
                ('To_Pin_Code', models.IntegerField()),
                ('Order_Status', models.CharField(default='Not yet delivered.', max_length=50)),
                ('Order_Type', models.CharField(max_length=50)),
                ('delivery_charge', models.IntegerField(blank=True, null=True)),
                ('Receiver_Name_Employee_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee2', to='courier_service.employees')),
                ('Sender_Employee_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee1', to='courier_service.employees')),
                ('User_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_service.user_details')),
            ],
        ),
    ]
