# Generated by Django 4.2.2 on 2023-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0015_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
