# Generated by Django 4.2.2 on 2023-10-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0017_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Order_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_service.cities'),
        ),
    ]
