# Generated by Django 4.2.2 on 2023-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_service', '0018_orders_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Receiver_Contact_Number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
